

enable = true
#unique name with dot notation for the package
name = "digitalme.example"

web_prefixes = "example"

[[loaders]]
giturl = "https://github.com/threefoldtech/digital_me/tree/development960/packages/system/example"
dest = ""

