enable = true
name = "digitalme_example" # unique name for the package
web_prefixes = "example"

[[loaders]]
giturl = "https://github.com/threefoldtech/digital_me/tree/development960/packages/system/example"
dest = ""

