enable = true
name = "digitalme_example" # unique name for the package

[[loaders]]
giturl = "https://github.com/threefoldtech/digital_me/tree/{{JS_BRANCH}}/packages/system/example"
dest = ""

[[arg]]
key = "JS_BRANCH"
val = "development_960"

