
[[docsites_loader]]
name = "foundation"
giturl = "https://github.com/threefoldfoundation/info_foundation/blob/development"

[[docsites_loader]]
name = "grid"
giturl = "https://github.com/threefoldfoundation/info_grid/blob/development"

[[docsites_loader]]
name = "tokens"
giturl = "https://github.com/threefoldfoundation/info_tokens/blob/development"

[[docsites_loader]]
name = "tech"
giturl = "https://github.com/threefoldfoundation/info_tech/blob/development"

[[docsites_loader]]
name = "tools"
gitur = "https://github.com/threefoldfoundation/info_tools/blob/master"
