enable = true
name = "digitalme_base" #unique name for the package

[[loaders]]
giturl = "https://github.com/threefoldtech/digital_me/tree/{{JS_BRANCH}}/packages/system/base"
dest = ""

[[loaders]]
giturl = "https://github.com/threefoldtech/jumpscale_weblibs/tree/master/static"
dest = "blueprints/base/static"


[[args]]
key = "JS_BRANCH"
val = "development_960"

