

enable = true
#unique name with dot notation for the package
name = "digitalme.chat"

web_prefixes = "chatflows"

[[loaders]]
giturl = "https://github.com/threefoldtech/digital_me/tree/development960/packages/system/chat"
dest = ""

